[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pharmweb"
authors = [{name = "Gerald", email = "gerald@easyrx.net"}]
dynamic = ["version", "description"]
